# Generated by Django 5.1.4 on 2024-12-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('summaries', models.TextField()),
                ('categories', models.CharField(max_length=100)),
            ],
        ),
    ]
